Xcopy . "../PokemonBattleWoods_v2.0.0" /E /H /C /I
echo "Removing Folders"
rmdir /s /q "../PokemonBattleWoods_v2.0.0/.git"
rmdir /s /q "../PokemonBattleWoods_v2.0.0/.idea"
rmdir /s /q "../PokemonBattleWoods_v2.0.0/Plugins/.idea"
rmdir /s /q "../PokemonBattleWoods_v2.0.0/Plugins/Custom Code/.idea"
rmdir /s /q "../PokemonBattleWoods_v2.0.0/move translations"
del "../PokemonBattleWoods_v2.0.0/.gitignore"
del "../PokemonBattleWoods_v2.0.0/deploy.bat"
del "../PokemonBattleWoods_v2.0.0/README.md"
del "../PokemonBattleWoods_v2.0.0/credits.txt"
del "../PokemonBattleWoods_v2.0.0/extendtext.txt"
del "../PokemonBattleWoods_v2.0.0/Gen8 Project Credits.txt"
del "../PokemonBattleWoods_v2.0.0/animmaker.txt"
del "../PokemonBattleWoods_v2.0.0/Essentials Docs Wiki.URL"
del "../PokemonBattleWoods_v2.0.0/townmapgen.html"
del "../PokemonBattleWoods_v2.0.0/extendtext.exe"
del "../PokemonBattleWoods_v2.0.0/animmaker.exe"